aws review

diff --git a/.github/workflows/review.yml b/.github/workflows/review.yml
--- a/.github/workflows/review.yml
+++ b/.github/workflows/review.yml
@@ -21,6 +21,52 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-west-2
+          github_token: ${{ github.token }}
+
+      - name: Associate Repository with CodeGuru Reviewer
+        run: |
+            aws codeguru-reviewer associate-repository --repository '{
+              "GitHubEnterpriseServer": {
+                "Name": "CaioVasconcellos-ServeRest-Actions",
+                "Owner": "CaioVasconcellos"
+                "ConnectionArn": "arn:aws:codeguru-reviewer:us-east-2:311141518949:association:1074ec9e-4e7c-4873-9372-e80ba765b936:code-review:RepositoryAnalysis-CaioVasconcellos_ServeRest-Actions-main-989f4215-2a22-45e6-bac0-59a25c26e4c8"
+              }
+            }'
+
+      - name: Test AWS Credentials
+        run: |
+            aws sts get-caller-identity
+
+      - name: Ensure S3 Bucket Exists
+        run: |
+          BUCKET_NAME="codeguru-reviewer-serverest-actions-oregon"
+          if ! aws s3 ls "s3://$BUCKET_NAME" 2>/dev/null; then
+            echo "Bucket does not exist, creating..."
+            aws s3 mb "s3://$BUCKET_NAME" --region us-west-2
+          else
+            echo "Bucket exists."
+          fi
+
+      - name: Check for Existing CodeGuru Association
+        id: check_association
+        run: |
+                ASSOCIATION_ARN=$(aws codeguru-reviewer list-repository-associations --query "RepositoryAssociationSummaries[?Name=='CaioVasconcellos-ServeRest-Actions'].AssociationArn" --output text)
+                if [[ -n "$ASSOCIATION_ARN" ]]; then
+                  echo "Found existing association: $ASSOCIATION_ARN"
+                  echo "ASSOCIATION_ARN=$ASSOCIATION_ARN" >> $GITHUB_ENV
+                else
+                  echo "No existing association found."
+                fi
+
+      - name: Remove Failed Association (if exists)
+        if: env.ASSOCIATION_ARN != ''
+        run: |
+                echo "Removing failed CodeGuru association..."
+                aws codeguru-reviewer disassociate-repository --association-arn $ASSOCIATION_ARN
+
+      - name: Reassociate Repository with CodeGuru
+        run: |
+                aws codeguru-reviewer associate-repository --repository Name="CaioVasconcellos-ServeRest-Actions",Type="GITHUB"
 
       - name: CodeGuru Reviewer
         uses: aws-actions/codeguru-reviewer@v1.1
